#spring:
#  profiles:
#    active: "oauth" # application-oauth.properties 사용
#
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    show-sql: true
#
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#        format_sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none #!!!!! 이거때문에 다시 만드는듯..
#
#server:
#  port: 8070
#
