spring:
  profiles:
    active: "oauth" # application-oauth.properties 사용

  session:
    store-type: jdbc # 세션 저장소를 jdbc로 선택 SPRING_SESSION, SPRING_SESSION_ATTRIBUTES DB생성 로그인을 하면 세션이 생성된다

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none #!!!!! 이거때문에 다시 만드는듯..

#  datasource:
#    url: jdbc:mysql://localhost:3306/book_manager
#    username: root
#    password:

server:
  port: 8070

