insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (0, 'Untitled (Rothko)', 'Untitled is a painting by the Russian-American Abstract expressionist artist Mark Rothko. It was painted in 1952. In common with Rothko''s other works from this period, it consists of large expanses of colour delineated by uneven, hazy shades.In 2014, Untitled was bought for $66 million by an anonymous buyer.', 66,1,3,1,1,1, 'https://www.jnilbo.com/photos/2021/01/23/2021012320102064134_l.jpg', 'Mark Rothko', 0, 3, 5);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (1, 'Orange and Yellow', 'Orange and Yellow reflects Mark Rothko’s mature style, in which two or three rectangles are set within a background that surrounds them all, but divides them gently from one another. The edges of the rectangles are never distinct, avoiding an optical break and allowing viewers’ eyes to move quietly from other area to another in a contemplative way.', 77,1060,4,1,1,1, 'https://uploads2.wikiart.org/images/mark-rothko/orange-and-yellow(1).jpg', 'Mark Rothko', 2, 1, 25);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (2, 'Multiform', 'Multiform (1948) belongs to a group of paintings by Mark Rothko, which signifies the transition toward his mature abstract style. These paintings, collectively known as ''Multiforms'', were painted between 1947 and 1949. The artist did not officially use the name ''Multiforms''; the term was adopted by art critics and historians to describe the group of paintings. In the specific case of Multiform, it seems the title was only used after Rothko''s death in 1970. It first appeared in the catalog for the Rothko exhibition held at the 1970 Venice Biennale. The catalog was put together by the staff of the Marlborough Gallery, who adopted the term ''Multiforms'', claiming it was casually used by Rothko to describe this group of artworks.', 102,1,5,1,1,1, 'https://uploads6.wikiart.org/images/mark-rothko/multiform-1948.jpg!Large.jpg', 'Mark Rothko', 2, 4, 40);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (3, 'Untitled (Yellow and Blue)', 'A painting by Mark Rothko titled “Untitled (Yellow and Blue)” in the year 1954, has been sold for $46.5 million. Mark Rothko is labeled as one of the most successful artists of the 20th century.', 11,16,1,1,1,1, 'http://cdn.shopify.com/s/files/1/0123/0156/6009/products/Untitled_Yellow_and_Blue_1200x1200.jpg?v=1585916830', 'Mark Rothko', 2, 3, 10);



insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (4, 'A Bigger Splash', 'This painting depicts a splash in a Californian swimming pool. Hockney first visited Los Angeles in 1963, a year after graduating from the Royal College of Art, London. He returned there in 1964 and remained, with only intermittent trips to Europe, until 1968 when he came back to London.', 102,105,3,1,1,1, 'https://t1.daumcdn.net/cfile/tistory/99EFE6375A65DFEA33', 'David Hockney', 0, 3, 10);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (5, 'Portrait of an Artist (Pool with Two Figures)', 'Portrait of an Artist (Pool with Two Figures) is a large acrylic-on-canvas pop art painting by British artist David Hockney, completed in May 1972. It measures 7 ft × 10 ft, and depicts two figures: one swimming underwater and one clothed male figure looking down at the swimmer.', 172,15,2,1,1,1, 'https://www.christies.com/img/LotImages/2018/NYR/2018_NYR_15974_0009C_000(david_hockney_portrait_of_an_artist).jpg?w=780', 'David Hockney', 2, 3, 10);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (6, 'American Collectors (Fred and Marcia Weisman)', 'American Collectors (Fred and Marcia Weisman) is a 1968 painting by British artist David Hockney. The painting is currently in the collection of the Art Institute of Chicago. It was accessioned by the museum in 1984 after being donated by Frederic G. Pick and his wife.', 84,1067,2,1,1,1, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkN4-MMbiu-etYsT2-r-eTwWjepZFDlrmgEe8Nv8zCf0YJm8ojHJhqRhZNTVG4ftzVIbE&usqp=CAU', 'David Hockney', 2, 1, 20);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (7, 'A Bigger Interior with Blue Terrace and Garden 2017', 'A Bigger Interior with Blue Terrace and Garden 2017 is a painting by British artist, David Hockney. Hockney completed the painting in 2017 and it is seen as one of his more famous modern works. It is 48x49 inches and was made using acrylic paint', 99,10060,1,1,1,1, 'https://az334033.vo.msecnd.net/images-3/interior-with-blue-terrace-and-garden-david-hockney-2017-20766bc0.jpg', 'David Hockney', 2, 1, 20);



insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`,`limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (8, 'Blue Nudes', 'The Blue Nudes is a series of color lithographs by Henri Matisse made from cut-outs depicting nude figures in various positions', 1102,1035,4,1,1,1, 'https://www.moma.org/d/assets/W1siZiIsIjIwMTcvMDYvMjIvODljcmkzc3NiNl8xNDEyNjMwNzM2XzY5MF9CbHVlX051ZGVzLmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ/1412630736_690_Blue_Nudes.jpg?sha=c93f67536c56e8aa', 'Henri Matisse', 2, 3, 20);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (9, 'Woman with a Hat', 'Woman with a Hat is a painting by Henri Matisse. An oil on canvas, it depicts Matisses wife, Amelie. It was painted in 1905 and exhibited at the Salon dAutomne during the fall of the same year, along with works by André Derain, Maurice de Vlaminck and several other artists known as "Fauves".', 1272,135,5,1,1,1, 'https://upload.wikimedia.org/wikipedia/en/f/fb/Matisse-Woman-with-a-Hat.jpg', 'Henri Matisse', 0, 3, 40);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (10, 'Music', 'Music is a wall-size painting made by Henri Matisse in 1910. The painting was commissioned by Sergei Shchukin, who hung it with Dance on the staircase of his Moscow mansion. Matisse made the painting without any preparatory sketches, and thus the painting bears many traces of modifications.', 8421,17,5,1,1,1, 'https://cdn.shopify.com/s/files/1/0969/9128/products/The_Music_La_Musique_1939_by_Henri_Matisse_Pls_get_correct_name_of_the_painting_-_PG_b4009eb5-2970-4ffa-bb78-6c7fff23a585.jpg?v=1479730459', 'Henri Matisse', 2, 1, 10);

insert into product (`id`, `product_name`, `description`, `price`, `purchase_count`, `rate_avg`, `limit_count`, `total_count`, `product_status`, `title_img`, `large_category`, `shipping_cost`, `shipping_due_date`, `sale_rate`) values (11, 'The Dance II', 'The Dance II by Henri Matisse is a triptych mural in the Barnes Foundation. It was created in 1932 at the request of Albert C. Barnes after he met Matisse in the United States.', 939,1,5,1,1,1, 'https://uploads7.wikiart.org/images/henri-matisse/dance-ii-1910.jpg!Large.jpg', 'Henri Matisse', 0, 3, 20);

insert into user(`id`, `email`, `name`, `picture`, `role`) values (1, 'facee22ge2@gmail.com', 'hee', 'http://img.segye.com/content/image/2021/06/18/20210618504877.jpg', 'SELLER');

insert into cart (`id`, `product_count`, `user_id`, `product_id`) values (0, 1, 1, 0);