create table cart (id bigint generated by default as identity, product_count integer, product_id bigint, user_id bigint, primary key (id));
create table product (id bigint generated by default as identity, description TEXT, large_category varchar(255), limit_count integer, price integer, product_name varchar(255), product_status integer, purchase_count integer, title_img varchar(255), total_count integer, primary key (id));
create table user (id bigint generated by default as identity, created_date timestamp, modified_date timestamp, email varchar(255) not null, name varchar(255) not null, picture varchar(255), role varchar(255) not null, primary key (id));

alter table cart add constraint FK3d704slv66tw6x5hmbm6p2x3u foreign key (product_id) references product;
alter table cart add constraint FKl70asp4l4w0jmbm1tqyofho4o foreign key (user_id) references user;