create table user (
    id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    email varchar(255) not null,
    name varchar(255) not null,
    picture varchar(255),
    role varchar(255) not null,
    primary key (id)
);

create table cart (
    id bigint generated by default as identity,
    product_count integer,
    primary key (id)
);

create table product (
    id bigint generated by default as identity,
    large_category varchar(255),
    description clob,
    limit_count integer,
    price integer,
    product_name varchar(255),
    product_status integer,
    purchase_count integer,
    title_img varchar(255),
    total_count integer,
    primary key (id)
);
